# Generated by Django 5.2.14 on 2026-06-03 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_rename_video_url_match_stream_url'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_shots', models.PositiveIntegerField(default=0)),
                ('away_shots', models.PositiveIntegerField(default=0)),
                ('home_shots_on_target', models.PositiveIntegerField(default=0)),
                ('away_shots_on_target', models.PositiveIntegerField(default=0)),
                ('home_corners', models.PositiveIntegerField(default=0)),
                ('away_corners', models.PositiveIntegerField(default=0)),
                ('home_possession', models.PositiveIntegerField(default=50)),
                ('away_possession', models.PositiveIntegerField(default=50)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='football.match')),
            ],
        ),
    ]
