# Generated by Django 5.2.14 on 2026-06-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_match_video_url_alter_standing_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='video_url',
            new_name='stream_url',
        ),
    ]
