# Generated by Django 5.2.14 on 2026-06-03 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_rename_video_url_match_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='defending',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='dribbling',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='overall',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='player',
            name='pace',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='passing',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='physical',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='shooting',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team')),
            ],
        ),
        migrations.CreateModel(
            name='LineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.player')),
            ],
        ),
    ]
