# Generated by Django 5.2.14 on 2026-06-03 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_player_defending_player_dribbling_player_overall_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineupplayer',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='lineupplayer',
            name='position_y',
        ),
        migrations.AddField(
            model_name='lineupplayer',
            name='position',
            field=models.CharField(default='GK', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('GOAL', 'Goal'), ('YELLOW', 'Yellow Card'), ('RED', 'Red Card'), ('SUB', 'Substitution')], max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.player')),
            ],
        ),
    ]
