# Generated by Django 5.2.14 on 2026-06-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_remove_lineupplayer_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
