# Generated by Django 5.2.14 on 2026-06-03 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_match_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='man_of_the_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.player'),
        ),
    ]
