# Generated by Django 5.2.14 on 2026-06-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_match_man_of_the_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
