# Generated by Django 5.2.14 on 2026-06-04 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_team_capacity_team_stadium'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Player rating from 0.0 to 10.0', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ratings', to='football.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_ratings', to='football.player')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
