# Generated by Django 5.2.14 on 2026-06-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_playermatchrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('GOAL', 'Goal'), ('ASSIST', 'Assist'), ('YELLOW', 'Yellow Card'), ('RED', 'Red Card'), ('SUB', 'Substitution')], max_length=20),
        ),
    ]
