# Generated by Django 5.2.14 on 2026-06-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_alter_matchevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupplayer',
            name='x_position',
            field=models.PositiveIntegerField(default=50, help_text='X position on field (0-100)'),
        ),
        migrations.AddField(
            model_name='lineupplayer',
            name='y_position',
            field=models.PositiveIntegerField(default=50, help_text='Y position on field (0-100)'),
        ),
    ]
