# Generated by Django 5.2.14 on 2026-06-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('football', '0011_lineupplayer_x_position_lineupplayer_y_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans', to='football.team'),
        ),
    ]
